import { useEffect,useMemo,useRef,useState } from 'react';
import { GHOST_SYMBOLS,TOTAL_GHOST_TRIALS,analyzeGhostTrials,plannedDuration,randomTarget,saveGhostSession,type GhostAnswer,type GhostSymbol,type GhostTrial } from './domain/ghost-frame';
import { requestGhostDebrief } from './domain/ghost-octopus';
import type { CharacterDebrief } from './domain/octopus';
type Phase='intro'|'calibration'|'ready'|'stimulus'|'answer'|'results';
const labels:Record<GhostAnswer,string>={triangle:'△',circle:'○',cross:'＋',spiral:'⌁',eye:'◉',wave:'≈',nothing:'RIEN'};
export default function GhostFrame({onBack}:{onBack:()=>void}){const [phase,setPhase]=useState<Phase>('intro');const [trial,setTrial]=useState(1);const [trials,setTrials]=useState<GhostTrial[]>([]);const [target,setTarget]=useState<GhostSymbol|null>(null);const [visible,setVisible]=useState(false);const [measuredMs,setMeasuredMs]=useState(0);const [debrief,setDebrief]=useState<CharacterDebrief[]>([]);const [source,setSource]=useState<'idle'|'loading'|'octopus'|'fallback'>('idle');const [selected,setSelected]=useState(0);const [interference,setInterference]=useState<'standard'|'strong'|'reduced'>('strong');const [pattern,setPattern]=useState(0);const [placement,setPlacement]=useState({x:50,y:50,size:100});const [durationMs,setDurationMs]=useState(120);const answerAt=useRef(0);const startedAt=useRef(new Date().toISOString());const aborted=useRef(false);const stats=useMemo(()=>analyzeGhostTrials(trials),[trials]);
useEffect(()=>()=>{aborted.current=true},[]);
function begin(){startedAt.current=new Date().toISOString();setTrials([]);setTrial(1);setPhase('ready')}
function run(){setPattern(Math.floor(Math.random()*4));const next=randomTarget();const duration=plannedDuration(trial);setDurationMs(duration);setPlacement({x:20+Math.floor(Math.random()*61),y:20+Math.floor(Math.random()*61),size:[45,60,80,100,125][Math.floor(Math.random()*5)]});setTarget(next);setPhase('stimulus');setVisible(false);const pre=500+Math.floor(Math.random()*500);window.setTimeout(()=>{if(aborted.current)return;const shown=performance.now();setVisible(true);window.setTimeout(()=>{if(aborted.current)return;setVisible(false);setMeasuredMs(performance.now()-shown);window.setTimeout(()=>{answerAt.current=performance.now();setPhase('answer')},220)},duration)},pre)}
function answer(value:GhostAnswer){const entry:GhostTrial={trial,target,answer:value,correct:target===null?value==='nothing':value===target,responseMs:Math.round(performance.now()-answerAt.current),plannedMs:durationMs,sizePct:placement.size,xPct:placement.x,yPct:placement.y,interference,measuredMs:Number(measuredMs.toFixed(1)),timestamp:new Date().toISOString()};const next=[...trials,entry];setTrials(next);if(trial<TOTAL_GHOST_TRIALS){setTrial(trial+1);setPhase('ready');return}const finalStats=analyzeGhostTrials(next);saveGhostSession({id:`ghost-${Date.now()}`,protocolId:'FLI-GHOST-02',protocolVersion:'1.1',startedAt:startedAt.current,completedAt:new Date().toISOString(),status:'completed',measurements:next,results:finalStats});setPhase('results');setSource('loading');requestGhostDebrief(finalStats).then(r=>{setDebrief(r.characters);setSource(r.source);setSelected(0)})}
const active=debrief[selected];return <main className="ghost-screen"><header className="ghost-head"><button className="ghost" onClick={onBack}>← LABO</button><div><p className="section-kicker">FLI-GHOST-02</p><h2>Ghost Frame</h2></div><span className="badge">PERCEPTION</span></header>
{phase==='intro'&&<section className="ghost-panel"><div className="ghost-orb ghost-intro-orb"><span>◉</span><small>GHOST / FRAME</small></div><h1>Something appeared.<br/>Probably.</h1><p>12 séquences. Une forme peut apparaître très brièvement — ou aucune. Vous répondez seulement après la séquence.</p><div className="ghost-warning">⚠ Séquences visuelles animées. Déconseillé en cas de photosensibilité ou d'épilepsie. Arrêtez immédiatement en cas d'inconfort.</div><button className="primary big" onClick={()=>setPhase('calibration')}>BEGIN CALIBRATION</button></section>}
{phase==='calibration'&&<section className="ghost-panel"><p className="section-kicker">CALIBRATION</p><h1>Bibliothèque de cibles</h1><div className="symbol-grid">{GHOST_SYMBOLS.map(s=><div key={s}><b>{labels[s]}</b><small>{s}</small></div>)}<div className="ghost-empty-symbol"><b>∅</b><small>nothing</small></div></div><p>Les essais sans cible sont des contrôles. Aucun résultat n'est révélé avant la fin des 12 essais.</p><fieldset className="ghost-interference-settings"><legend>PERTURBATIONS VISUELLES</legend><div>{(['reduced','standard','strong'] as const).map(level=><button type="button" key={level} className={interference===level?'active':''} aria-pressed={interference===level} onClick={()=>setInterference(level)}>{level==='reduced'?'RÉDUITES':level==='standard'?'STANDARD':'INTENSES'}</button>)}</div><small>Les mêmes filtres sont appliqués aux essais avec ou sans cible. Aucun flash stroboscopique.</small></fieldset><button className="primary big" onClick={begin}>START EXPERIMENT</button></section>}
{phase==='ready'&&<section className="ghost-panel center"><p className="trial-label">TRIAL {trial} / {TOTAL_GHOST_TRIALS}</p><div className="ghost-orb small ghost-ready-orb"><span>{trial.toString().padStart(2,"0")}</span><small>FRAME / {TOTAL_GHOST_TRIALS}</small></div><p>Fixez le centre, mais surveillez tout le champ : taille, position et durée varient.</p><button className="primary big" onClick={run}>LANCER LA SÉQUENCE</button></section>}
{phase==='stimulus'&&<section className={`ghost-field ghost-interference-${interference} ghost-pattern-${pattern}`}><button className="stop-ghost" onClick={onBack}>■ STOP</button><div className="noise n1"/><div className="noise n2"/><div className="ghost-reticle" aria-hidden="true"><i/><i/><i/><i/></div><div className="fixation">·</div>{visible&&target&&<div className="flash-symbol ghost-variable-symbol" style={{left:`${placement.x}%`,top:`${placement.y}%`,fontSize:`clamp(28px, ${placement.size*.25}vw, ${placement.size*1.8}px)`}}>{labels[target]}</div>}<div className="ghost-veil ghost-veil-grain" aria-hidden="true"/><div className="ghost-veil ghost-veil-scan" aria-hidden="true"/><div className="ghost-veil ghost-veil-echo" aria-hidden="true"/><small>TRIAL {trial} // SIGNAL ACQUISITION</small></section>}
{phase==='answer'&&<section className="ghost-panel"><p className="trial-label">TRIAL {trial} / {TOTAL_GHOST_TRIALS}</p><h1>WHAT DID YOU SEE?</h1><p className="ghost-answer-hint">Sélectionnez le symbole perçu, ou indiquez qu’aucune forme n’est apparue.</p><div className="answer-grid">{GHOST_SYMBOLS.map(s=><button key={s} onClick={()=>answer(s)} aria-label={s}><b>{labels[s]}</b><small>{s}</small></button>)}<button className="nothing" onClick={()=>answer('nothing')}><b>∅</b><span>RIEN VU</span></button></div><small>Aucun feedback avant la fin : votre stratégie ne peut pas s'adapter aux résultats.</small></section>}
{phase==='results'&&<section className="ghost-panel results"><p className="section-kicker">DATA // SESSION COMPLETE</p><div className="ghost-result-hero"><small>PRÉCISION GLOBALE</small><h1>{stats.accuracy}<span>%</span></h1><p>{stats.correct} réponses exactes sur {stats.total} essais</p></div><div className="ghost-stats" aria-label="Mesures de la session"><Stat n={stats.hits} l="HITS"/><Stat n={stats.misses} l="MISSES"/><Stat n={stats.falsePositives} l="FALSE +"/><Stat n={stats.correctRejections} l="CORRECT ∅"/><Stat n={stats.meanResponseMs} l="RESPONSE ms"/><Stat n={stats.meanStimulusMs} l="DISPLAY ms"/></div><p className="data-note">Un faux positif = une forme rapportée pendant un essai sans cible. Ce n'est pas une détection paranormale.</p><div className="character-tabs">{debrief.map((c,i)=><button key={c.name} className={i===selected?'active':''} onClick={()=>setSelected(i)}>{c.name}</button>)}</div><div className="octopus-comment">{source==='loading'?<p>Octopus consulte Blacklace…</p>:active?<><header><strong>{active.name}</strong><span>{active.role}</span></header><p>{active.text}</p><small>{source==='octopus'?'OCTOPUS · données de cette session':'MODE SECOURS LOCAL'}</small></>:<p>Débrief indisponible.</p>}</div><button className="primary big" onClick={begin}>NOUVELLE SESSION</button></section>}</main>}
function Stat({n,l}:{n:number;l:string}){return <div><strong>{n}</strong><span>{l}</span></div>}
