import {useState} from 'react';
import LabJourney from './LabJourney';
type Page='experiences'|'parcours'|'archives'|'univers'|'reglages'|'premium';
type Lang='fr'|'en'|'es';
const LINKS=[{name:'Le Bazar du Feuch',url:'https://benoitlub.github.io/bazar-du-feuch/',desc:['Toutes les créations sur les étagères du laboratoire.','All creations on the laboratory shelves.','Todas las creaciones en las estanterías del laboratorio.']},{name:'Blacklace Dice',url:'https://benoitlub.github.io/blacklace-dice/',desc:['Missions, personnages et défis.','Missions, characters and challenges.','Misiones, personajes y desafíos.']},{name:'420 Dice Game',url:'https://benoitlub.github.io/420-dice-game-reboot/',desc:['Trois dés et des gages à partager.','Three dice and shared challenges.','Tres dados y retos compartidos.']},{name:'Blacklace Live',url:'https://benoitlub.github.io/blacklace-echo/',desc:['L’île, ses signaux et ses histoires.','The island, its signals and stories.','La isla, sus señales e historias.']}];
const COPY={fr:{tabs:['Expériences','Parcours','Archives','Univers','Réglages','Premium'],intro:['Bienvenue au Feuch Lab','Expérimente, observe, doute. Marty s’occupe du reste.','Garde la trace de tes explorations et découvre le laboratoire.','Le Feuch Lab est une porte vers les jeux et histoires de Blacklace.'],next:'Suivant',start:'Entrer au laboratoire',skip:'Passer',journey:'Parcours du laboratoire',archive:'Journal local',world:'Explorer Blacklace',settings:'Préférences',premium:'Carte membre Blacklace',soon:'Les droits inter-jeux et le paiement ne sont pas encore activés.',restore:'Restauration des achats : bientôt disponible.',note:'Ces liens ouvrent des applications indépendantes. Aucun achat ne les débloque automatiquement.',reset:'Revoir la présentation'},en:{tabs:['Experiments','Journey','Archive','Universe','Settings','Premium'],intro:['Welcome to Feuch Lab','Experiment, observe, doubt. Marty handles the rest.','Keep track of your explorations and discover the lab.','Feuch Lab opens the door to Blacklace games and stories.'],next:'Next',start:'Enter the lab',skip:'Skip',journey:'Laboratory journey',archive:'Local journal',world:'Explore Blacklace',settings:'Preferences',premium:'Blacklace membership',soon:'Cross-game entitlements and payment are not active yet.',restore:'Purchase restoration: coming soon.',note:'These links open independent apps. A purchase does not automatically unlock them.',reset:'Replay introduction'},es:{tabs:['Experimentos','Recorrido','Archivo','Universo','Ajustes','Premium'],intro:['Bienvenido a Feuch Lab','Experimenta, observa, duda. Marty se ocupa del resto.','Guarda tus exploraciones y descubre el laboratorio.','Feuch Lab abre la puerta a los juegos e historias de Blacklace.'],next:'Siguiente',start:'Entrar al laboratorio',skip:'Saltar',journey:'Recorrido del laboratorio',archive:'Diario local',world:'Explorar Blacklace',settings:'Preferencias',premium:'Membresía Blacklace',soon:'Los derechos entre juegos y el pago aún no están activos.',restore:'Restaurar compras: próximamente.',note:'Estos enlaces abren aplicaciones independientes. La compra no las desbloquea automáticamente.',reset:'Repetir presentación'}} as const;
const key='fli_portal_onboard_v1';
export default function LabPortal({page,setPage}:{page:Page;setPage:(p:Page)=>void}) {
 const [lang,setLang]=useState<Lang>(()=>{const v=localStorage.getItem('fli_lang');return v==='en'||v==='es'?v:'fr'});
 const [theme,setTheme]=useState<'dark'|'light'>(()=>localStorage.getItem('fli_theme')==='light'?'light':'dark');
 const [intro,setIntro]=useState(()=>!localStorage.getItem(key));
 const [step,setStep]=useState(0);
 const [infoOpen,setInfoOpen]=useState(false);
 const t=COPY[lang],pages:Page[]=['experiences','parcours','archives','univers','reglages','premium'];
 const close=()=>{localStorage.setItem(key,'1');setIntro(false)};
 const changeLang=(v:Lang)=>{setLang(v);localStorage.setItem('fli_lang',v)};
 const toggleTheme=()=>{const v=theme==='dark'?'light':'dark';setTheme(v);localStorage.setItem('fli_theme',v)};
 return <div className={'fli-portal '+(theme==='light'?'fli-light':'')}>
 <header className="fli-site-header"><a className="fli-site-home" href="https://benoitlub.github.io/bazar-du-feuch/" aria-label="Le Bazar du Feuch">⌂</a><div className="fli-site-brand"><span className="fli-site-mark">△</span><strong>FEUCH <span>LAB</span></strong></div><div className="fli-site-actions"><button className="fli-site-tool" type="button" onClick={toggleTheme} aria-label={theme==='dark'?'Activer le mode clair':'Activer le mode sombre'} title={theme==='dark'?'Mode clair':'Mode sombre'}>{theme==='dark'?'☼':'☾'}</button><div className="fli-site-languages" role="group" aria-label="Langue">{(['fr','es','en'] as const).map(v=><button type="button" key={v} className={lang===v?'active':''} aria-label={v==='fr'?'Français':v==='es'?'Español':'English'} aria-pressed={lang===v} onClick={()=>changeLang(v)}>{v.toUpperCase()}</button>)}</div><button className="fli-site-tool fli-info-trigger" type="button" aria-label="Informations sur Feuch Lab" title="À propos" onClick={()=>setInfoOpen(true)}>ⓘ</button><a className="fli-site-support" href="https://ko-fi.com/feuchinstitut" target="_blank" rel="noopener noreferrer" aria-label="Soutenir Feuch Lab sur Ko-fi">☕</a></div></header>
 <nav className="fli-portal-nav" aria-label="Feuch Lab">{pages.map((p,i)=><button key={p} className={page===p?'selected':''} onClick={()=>setPage(p)}>{t.tabs[i]}</button>)}</nav>
 {page==='parcours'&&<section className="fli-portal-panel"><h2>{t.journey}</h2><LabJourney/></section>}
 {page==='archives'&&<section className="fli-portal-panel"><h2>{t.archive}</h2><LabJourney archive/></section>}
 {page==='univers'&&<section className="fli-portal-panel"><h2>{t.world}</h2><p><a href="https://benoitlub.github.io/bazar-du-feuch/" target="_blank" rel="noopener noreferrer">↗ Le Bazar du Feuch — toutes les créations</a></p><p>{t.note}</p><div className="fli-world-list">{LINKS.map(x=><a key={x.name} href={x.url} target="_blank" rel="noopener noreferrer"><strong>{x.name} ↗</strong><span>{x.desc[lang==='fr'?0:lang==='en'?1:2]}</span></a>)}</div></section>}
 {page==='reglages'&&<section className="fli-portal-panel"><h2>{t.settings}</h2><label>Langue / Language / Idioma <select value={lang} onChange={e=>{const v=e.target.value as Lang;setLang(v);localStorage.setItem('fli_lang',v)}}><option value="fr">Français</option><option value="en">English</option><option value="es">Español</option></select></label><label>Thème / Theme / Tema <select value={theme} onChange={e=>{const v=e.target.value as 'dark'|'light';setTheme(v);localStorage.setItem('fli_theme',v)}}><option value="dark">Dark Lab</option><option value="light">Light Lab</option></select></label><button onClick={()=>{setStep(0);setIntro(true)}}>{t.reset}</button><small>{lang==='fr'?'Ces préférences concernent le portail ; les protocoles conservent actuellement leurs propres interfaces.':lang==='es'?'Estas preferencias afectan al portal; los protocolos mantienen sus interfaces.':'These preferences affect the portal; protocols retain their own interfaces.'}</small></section>}

 {page==='premium'&&<section className="fli-portal-panel fli-premium"><span>FEUCH INSTITUTE · BLACKLACE</span><h2>{t.premium}</h2><strong className="fli-price">4,20 €</strong><p>{lang==='fr'?'Achat unique envisagé · sans abonnement':lang==='es'?'Compra única prevista · sin suscripción':'Planned one-time purchase · no subscription'}</p><p>{t.soon}</p><button disabled>PayPal — 4,20 €</button><small>{t.restore}</small><p>{t.note}</p></section>}
 <div className="fli-site-footer"><span>© FEUCH LAB · BLACKLACE</span><a href="https://benoitlub.github.io/bazar-du-feuch/" target="_blank" rel="noopener noreferrer">BAZAR ↗</a><a href="https://ko-fi.com/feuchinstitut" target="_blank" rel="noopener noreferrer">☕ KO-FI ↗</a></div>
 {infoOpen&&<div className="fli-info-backdrop" onClick={()=>setInfoOpen(false)}><section className="fli-info-sheet" role="dialog" aria-modal="true" aria-label="À propos de Feuch Lab" onClick={e=>e.stopPropagation()}><div className="fli-info-handle"/><button className="fli-info-close" type="button" aria-label="Fermer" onClick={()=>setInfoOpen(false)}>×</button><div className="fli-info-hero"><span className="fli-info-emblem">△</span><h2>Feuch Lab</h2><em>« Expérimente. Observe. Doute. »</em></div><div className="fli-info-body"><h3>LE CONCEPT</h3><p>Un laboratoire ludique de perception, d’intuition et de hasard, dans l’univers de Blacklace Island. Chaque expérience invite à faire un choix, observer ce qui se passe et conserver une trace de ses résultats.</p><h3>LES EXPÉRIENCES</h3><p>Prédiction, symboles furtifs, perception visuelle, mémoire, timing et expériences à deux téléphones. Certains protocoles comportent des stimuli très brefs ou des perturbations visuelles : adapte leur intensité à ton confort.</p><h3>COMMENT LIRE LES RÉSULTATS ?</h3><p>Les scores sont des observations ludiques, pas des preuves de capacités paranormales ni un diagnostic. Le hasard, l’attention et les conditions d’affichage peuvent influencer les résultats.</p><h3>LE CRÉATEUR</h3><p>Feuch Lab est une création Blacklace / Pro.Hibited. Une expérience née de l’envie de jouer avec l’incertitude, les perceptions et les histoires.</p><a className="fli-info-contact" href="mailto:prohibitedvlc@gmail.com">↗ Prendre contact</a><a className="fli-info-bazar" href="https://benoitlub.github.io/bazar-du-feuch/" target="_blank" rel="noopener noreferrer">Explorer le Bazar du Feuch ↗</a></div></section></div>}
 {intro&&<div className="fli-intro-backdrop" role="presentation"><section className="fli-intro-dialog" role="dialog" aria-modal="true" aria-label={t.intro[0]}><button className="fli-intro-skip" onClick={close}>{t.skip} ×</button><div className="fli-intro-mark">△</div><small>FEUCH INSTITUTE · {step+1}/4</small><h2>{t.intro[step]}</h2><div className="fli-intro-dots">{t.intro.map((_,i)=><span key={i} className={i===step?'active':''}/>)}</div><button className="fli-intro-next" onClick={()=>step===3?close():setStep(step+1)}>{step===3?t.start:t.next} →</button></section></div>}
 </div>;
}
