import { useMemo, useState } from 'react';
import App from './App';
import SilentLink from './SilentLink';
import GhostFrame from './GhostFrame';
import InstantExperiment from './InstantExperiments';
import TrainingLab from './TrainingLab';
import Pineal from './Pineal';
import QuickGames from './QuickGames';
type Protocol='library'|'walk'|'silent'|'ghost'|'predict'|'feel'|'stereo'|'oculus'|'hands'|'pineal'|'zener'|'stop'|'flash'|'marty';
export default function LabRoot(){const initial=useMemo<Protocol>(()=>{const q=new URLSearchParams(location.search);if(q.has('room')||q.get('protocol')==='silent')return'silent';const p=q.get('protocol') as Protocol;if(['ghost','predict','feel','stereo','oculus','hands','pineal','zener','stop','flash','marty'].includes(p))return p;return'library'},[]);const[protocol,setProtocol]=useState<Protocol>(initial);const home=()=>{history.replaceState(null,'',location.pathname);setProtocol('library')};const open=(p:Protocol)=>{history.replaceState(null,'',`${location.pathname}?protocol=${p}`);setProtocol(p)};
if(protocol==='walk')return <div className="protocol-wrap"><button className="lab-home-fab" onClick={home}>⌂ LAB</button><App/></div>;if(protocol==='silent')return <SilentLink onBack={home}/>;if(protocol==='ghost')return <GhostFrame onBack={home}/>;if(protocol==='predict'||protocol==='feel')return <InstantExperiment mode={protocol} onBack={home}/>;if(protocol==='stereo'||protocol==='oculus'||protocol==='hands')return <TrainingLab kind={protocol} onBack={home}/>;if(protocol==='pineal')return <Pineal onBack={home}/>;if(protocol==='zener'||protocol==='stop'||protocol==='flash'||protocol==='marty')return <QuickGames game={protocol} onBack={home}/>;
const cards:[Protocol,string,string,string,string,string][]=[['predict','FLI-PREDICT-10','←?','Before It Happens','Choisis gauche ou droite avant la révélation.','10 ESSAIS · INSTANT'],['zener','FLI-ZENER-20','☆','What’s Behind?','Devine le symbole caché parmi cinq possibilités.','20 ESSAIS · 20 % HASARD'],['stop','FLI-STOP-10','●','Feel It Now','Trouve le moment précis d’une cible secrète.','10 ESSAIS · TIMING'],['flash','FLI-FLASH-12','⚡','Did You See It?','Identifie un symbole affiché en un éclair.','12 ESSAIS · PERCEPTION'],['marty','FLI-MARTY-10','⊙','Marty’s Button','Ne touche pas au bouton. Enfin, presque.','10 ESSAIS · FEUCH'],['feel','FLI-FEEL-10','?∅','Something / Nothing','Devine laquelle des deux conditions a été tirée.','10 ESSAIS · INSTANT'],['ghost','FLI-GHOST-02','◉','Ghost Frame','Détecte des stimuli brefs et les faux positifs.','20 ESSAIS · PERCEPTION'],['hands','FLI-HAND','△','Hand Codex','Mémorise et reproduis une suite de sigils.','3 NIVEAUX · MÉMOIRE'],['walk','FLI-MW-06','6','Marty Walk','Six pas, des capteurs et un débrief Blacklace.','MOUVEMENT · CAPTEURS'],['silent','FLI-B2B-20','A↔B','Silent Link','Deux téléphones, une cible secrète, vingt essais.','DUO · 2 TÉLÉPHONES'],['stereo','FLI-STEREO','◎◎','Third Eye','Explore un autostéréogramme en relief.','LAB · VISION 3D'],['pineal','FLI-PINEAL','◉△','Third Eye / Pineal','Observe et décris tes perceptions visuelles.','LAB · PERCEPTION'],['oculus','FLI-OCULUS','◉','Oculus','Exercice de poursuite visuelle douce.','LAB · PROTOTYPE']];
const renderCard=([p,id,icon,title,desc,meta]:typeof cards[number])=><button key={p} className="fli-game-card" onClick={()=>open(p)}><span className="fli-game-icon" aria-hidden="true">{icon}</span><span className="fli-game-copy"><span className="fli-game-id">{id}</span><strong>{title}</strong><span className="fli-game-description">{desc}</span><span className="fli-game-meta">{meta}</span></span><span className="fli-game-arrow" aria-hidden="true">↗</span></button>;
return <main className="fli-library"><header className="fli-library-header"><div className="fli-brand"><span className="fli-brand-mark">△</span><span>FEUCH LAB <em>INSTITUTE</em></span></div><span className="fli-brand-tag">BLACKLACE</span></header><div className="fli-library-intro"><span className="fli-overline">THE EXPERIMENTS / 001—013</span><h1>Choisis ton<br/><em>expérience.</em></h1><p>Une intuition. Un essai. Un résultat. Déraper avec méthode.</p></div><section className="fli-library-section"><div className="fli-section-title"><h2>À jouer maintenant</h2><span>10 PROTOCOLES</span></div><div className="fli-game-list">{cards.slice(0,10).map(renderCard)}</div></section><details className="fli-lab-section"><summary><span><small>RECHERCHE & PROTOTYPES</small><strong>Le laboratoire</strong><em>3 expériences exploratoires</em></span><span className="fli-lab-chevron">＋</span></summary><div className="fli-game-list">{cards.slice(10).map(renderCard)}</div></details><div className="fli-archive"><span className="fli-game-icon">▤</span><span><small>COMING SOON</small><strong>The Archive</strong><p>Comparer les sessions et retrouver les vrais motifs.</p></span></div><footer>EXTRAORDINARY CLAIMS · ORDINARY DATA</footer></main>}
