import { useMemo, useState } from 'react';
import App from './App';
import SilentLink from './SilentLink';
import GhostFrame from './GhostFrame';
import InstantExperiment from './InstantExperiments';
import TrainingLab from './TrainingLab';
import Pineal from './Pineal';
import QuickGames from './QuickGames';
type Protocol='library'|'walk'|'silent'|'ghost'|'predict'|'feel'|'stereo'|'oculus'|'hands'|'pineal'|'zener'|'stop'|'flash'|'marty';
export default function LabRoot(){const initial=useMemo<Protocol>(()=>{const q=new URLSearchParams(location.search);if(q.has('room')||q.get('protocol')==='silent')return'silent';const p=q.get('protocol') as Protocol;if(['ghost','predict','feel','stereo','oculus','hands','pineal','zener','stop','flash','marty'].includes(p))return p;return'library'},[]);const[protocol,setProtocol]=useState<Protocol>(initial);const home=()=>{history.replaceState(null,'',location.pathname);setProtocol('library')};const open=(p:Protocol)=>{history.replaceState(null,'',`${location.pathname}?protocol=${p}`);setProtocol(p)};
if(protocol==='walk')return <div className="protocol-wrap"><button className="lab-home-fab" onClick={home}>⌂ LAB</button><App/></div>;if(protocol==='silent')return <SilentLink onBack={home}/>;if(protocol==='ghost')return <GhostFrame onBack={home}/>;if(protocol==='predict'||protocol==='feel')return <InstantExperiment mode={protocol} onBack={home}/>;if(protocol==='stereo'||protocol==='oculus'||protocol==='hands')return <TrainingLab kind={protocol} onBack={home}/>;if(protocol==='pineal')return <Pineal onBack={home}/>;if(protocol==='zener'||protocol==='stop'||protocol==='flash'||protocol==='marty')return <QuickGames game={protocol} onBack={home}/>;
const cards:[Protocol,string,string,string,string,string][]=[['predict','FLI-PREDICT-10','←?','Before It Happens','Choisir avant que la cible aléatoire n’existe.','10 ESSAIS · INSTANT'],['zener','FLI-ZENER-20','☆','What’s Behind?','Deviner un symbole parmi cinq avant sa révélation.','20 ESSAIS · 20% HASARD'],['stop','FLI-STOP-10','●','Feel It Now','Appuyer au moment d’une cible temporelle secrète.','10 ESSAIS · TIMING'],['flash','FLI-FLASH-12','⚡','Did You See It?','Identifier un symbole affiché quelques millisecondes.','12 ESSAIS · PERCEPTION'],['marty','FLI-MARTY-10','⊙','Marty’s Button','Ne pas appuyer. Sauf exactement quand il faut.','10 ESSAIS · FEUCH'],['feel','FLI-FEEL-10','?∅','Something / Nothing','Deux conditions identiques. Deviner laquelle a été tirée.','10 ESSAIS · INSTANT'],['ghost','FLI-GHOST-02','◉','Ghost Frame','Stimuli brefs, contrôles et faux positifs mesurés.','EXPÉRIENCE · PERCEPTION'],['hands','FLI-HAND','△','Hand Codex','Mémoriser puis reproduire les sigils Blacklace.','TRAINING · MEMORY'],['walk','FLI-MW-06','6','Marty Walk','Six pas, accéléromètre et débrief Blacklace.','EXPÉRIENCE · MOTION'],['silent','FLI-B2B-20','A↔B','Silent Link','20 essais OUI/NON, deux téléphones, cible côté serveur.','EXPÉRIENCE · 2 TÉLÉPHONES'],['stereo','FLI-STEREO','◎◎','Third Eye','Autostéréogramme et fusion stéréoscopique progressive.','LAB · VISION 3D'],['pineal','FLI-PINEAL','◉△','Third Eye / Pineal','Observer puis décrire des phénomènes visuels sans réponses suggérées.','LAB · PERCEPTION'],['oculus','FLI-OCULUS','◉','Oculus','Poursuite visuelle douce, clignement et coordination.','LAB · PROTOTYPE']];return <main className="lab-library"><header className="library-head"><div className="hero-mark">△</div><div><p className="eyebrow">FEUCH LAB INSTITUTE</p><h1>Protocol Library</h1><p>Mesurer d'abord. Interpréter ensuite. Déraper avec méthode.</p></div><span className="badge">BLACKLACE</span></header><section className="library-grid">{cards.map(([p,id,icon,title,desc,meta])=><button key={p} className="protocol-card active" onClick={()=>p==='walk'?setProtocol(p):open(p)}><span className="protocol-id">{id}</span><div className="protocol-icon">{icon}</div><h2>{title}</h2><p>{desc}</p><small>{meta}</small></button>)}<article className="protocol-card dormant"><span className="protocol-id">THE ARCHIVE</span><div className="protocol-icon">▤</div><h2>Archive</h2><p>Comparer les sessions et rechercher des motifs réellement reproductibles.</p><small>BIENTÔT</small></article></section><footer>FEUCH LAB // EXTRAORDINARY CLAIMS, ORDINARY DATA</footer></main>}
