import {useMemo,useRef,useState} from 'react';
type Game='zener'|'stop'|'flash'|'marty';
const Z=[['○','CIRCLE'],['＋','CROSS'],['≈','WAVES'],['□','SQUARE'],['☆','STAR']] as const;
const rand=(n:number)=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%n};
function pct(n:number,d:number){return d?((100*n/d).toFixed(1).replace('.0','')):'0'}
function binTail(k:number,n:number,p:number){let s=0;const C=(n:number,r:number)=>{let x=1;for(let i=1;i<=r;i++)x=x*(n-r+i)/i;return x};for(let i=k;i<=n;i++)s+=C(n,i)*p**i*(1-p)**(n-i);return s}
function Head({id,title,onBack}:{id:string;title:string;onBack:()=>void}){return <header className="quick-head"><button onClick={onBack}>← LABO</button><div><small>{id} · EXPERIMENT</small><h2>{title}</h2></div></header>}
function Summary({hits,n,chance,restart}:{hits:number;n:number;chance:number;restart:()=>void}){const p=binTail(hits,n,chance);return <div className="quick-summary"><small>SESSION TERMINÉE</small><strong>{pct(hits,n)}%</strong><h2>{hits}/{n} correspondances</h2><p>Hasard attendu : {(chance*100).toFixed(0)} %</p><p>Probabilité d’obtenir au moins ce score sous le hasard : {(p*100).toFixed(2)} %</p><button className="primary big" onClick={restart}>REJOUER</button></div>}
export default function QuickGames({game,onBack}:{game:Game;onBack:()=>void}){if(game==='zener')return <Zener onBack={onBack}/>;if(game==='stop')return <Stop onBack={onBack}/>;if(game==='flash')return <Flash onBack={onBack}/>;return <Marty onBack={onBack}/>}
function Zener({onBack}:{onBack:()=>void}){const[trial,setTrial]=useState(0),[hits,setHits]=useState(0),[reveal,setReveal]=useState<number|null>(null);const n=20;function pick(i:number){if(reveal!==null)return;const t=rand(5);setReveal(t);if(i===t)setHits(h=>h+1)}function next(){setReveal(null);setTrial(t=>t+1)}function reset(){setTrial(0);setHits(0);setReveal(null)}return <main className="quick-screen"><Head id="FLI-ZENER-20" title="What's Behind?" onBack={onBack}/>{trial>=n?<Summary hits={hits} n={n} chance={.2} restart={reset}/>:<section className="quick-panel"><p className="quick-count">{trial+1}/{n}</p><h1>QUEL SYMBOLE EST DERRIÈRE ?</h1><div className="zener-grid">{Z.map(([s,l],i)=><button key={l} onClick={()=>pick(i)}><b>{s}</b><span>{l}</span></button>)}</div>{reveal!==null&&<div className="reveal">CIBLE <b>{Z[reveal][0]}</b><button className="primary" onClick={next}>SUIVANT</button></div>}<small>Choix forcé à 5 possibilités · hasard attendu 20 %.</small></section>}</main>}
function Stop({onBack}:{onBack:()=>void}){const[start,setStart]=useState<number|null>(null),[target,setTarget]=useState(0),[errors,setErrors]=useState<number[]>([]);const n=10;function begin(){setTarget(2000+rand(6001));setStart(performance.now())}function hit(){if(start===null)return;setErrors(e=>[...e,Math.round(performance.now()-start-target)]);setStart(null)}const last=errors.at(-1);const avg=useMemo(()=>errors.length?Math.round(errors.reduce((a,b)=>a+Math.abs(b),0)/errors.length):0,[errors]);return <main className="quick-screen"><Head id="FLI-STOP-10" title="Feel It Now" onBack={onBack}/><section className="quick-panel">{errors.length>=n?<><div className="quick-summary"><small>ERREUR ABSOLUE MOYENNE</small><strong>{avg} ms</strong><p>Meilleur : {Math.min(...errors.map(Math.abs))} ms</p><button className="primary big" onClick={()=>setErrors([])}>REJOUER</button></div></>:<><p className="quick-count">{errors.length+1}/{n}</p><h1>RESSENS LE MOMENT</h1><p>Une cible temporelle secrète est fixée. Appuie quand tu penses qu’elle arrive.</p>{start===null?<button className="orb" onClick={begin}>PRÊT</button>:<button className="orb live" onClick={hit}>NOW</button>}{last!==undefined&&start===null&&<p className="instant-result">{last===0?'PILE !':last>0?`+${last} ms`:`${last} ms`}</p>}<small>La cible est générée avant chaque essai, entre 2 et 8 secondes.</small></>}</section></main>}
function Flash({onBack}:{onBack:()=>void}){const[trial,setTrial]=useState(0),[hits,setHits]=useState(0),[target,setTarget]=useState<number|null>(null),[visible,setVisible]=useState(false),[answering,setAnswering]=useState(false);const timer=useRef<number>();const n=12,duration=Math.max(16,80-trial*6);function launch(){const t=rand(4);setTarget(t);setVisible(true);setAnswering(false);timer.current=window.setTimeout(()=>{setVisible(false);setAnswering(true)},duration)}function answer(i:number){if(!answering||target===null)return;if(i===target)setHits(h=>h+1);setTrial(t=>t+1);setAnswering(false);setTarget(null)}function reset(){setTrial(0);setHits(0);setTarget(null);setVisible(false);setAnswering(false)}return <main className="quick-screen"><Head id="FLI-FLASH-12" title="Did You See It?" onBack={onBack}/>{trial>=n?<Summary hits={hits} n={n} chance={.25} restart={reset}/>:<section className="quick-panel"><p className="quick-count">{trial+1}/{n} · {duration} ms</p><div className="flash-box">{visible&&target!==null?<b>{['△','○','◇','＋'][target]}</b>:<span>·</span>}</div>{!visible&&!answering&&<button className="primary big" onClick={launch}>FLASH</button>}{answering&&<div className="flash-answers">{['△','○','◇','＋'].map((s,i)=><button key={s} onClick={()=>answer(i)}>{s}</button>)}</div>}<small>Identification visuelle brève · 4 choix · hasard attendu 25 %.</small></section>}</main>}
function Marty({onBack}:{onBack:()=>void}){const[start,setStart]=useState<number|null>(null),[target,setTarget]=useState(0),[errors,setErrors]=useState<number[]>([]);const n=10;function arm(){setTarget(1200+rand(6801));setStart(performance.now())}function press(){if(start===null)return;setErrors(e=>[...e,Math.round(performance.now()-start-target)]);setStart(null)}const last=errors.at(-1);return <main className="quick-screen"><Head id="FLI-MARTY-10" title="Marty's Button" onBack={onBack}/><section className="quick-panel">{errors.length>=n?<div className="quick-summary"><small>LE FEUCH A TRANCHÉ</small><strong>{Math.min(...errors.map(Math.abs))} ms</strong><h2>MEILLEUR PASSAGE</h2><p>Erreur médiane approximative : {Math.round([...errors].map(Math.abs).sort((a,b)=>a-b)[Math.floor(errors.length/2)])} ms</p><button className="primary big" onClick={()=>setErrors([])}>ENCORE</button></div>:<><p className="quick-count">{errors.length+1}/{n}</p><h1>NE PAS APPUYER.</h1><p>Enfin… sauf quand tu sens que le Feuch passe.</p>{start===null?<button className="marty-button" onClick={arm}>ARMER<br/>LE FEUCH</button>:<button className="marty-button armed" onClick={press}>NE PAS<br/>APPUYER</button>}{last!==undefined&&start===null&&<p className="instant-result">{Math.abs(last)<=100?'MARTY APPROUVE.':`FEUCH MANQUÉ DE ${Math.abs(last)} ms ${last<0?'TROP TÔT':'TROP TARD'}`}</p>}<small>La cible temporelle est secrète et fixée avant ton action. Marty, lui, prétend que ce détail est secondaire.</small></>}</section></main>}
