import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
type Training='stereo'|'oculus'|'hands';
type GestureId='TRIANGLE'|'CIRCLE'|'SPIRAL'|'GATE';
const gestureDefs:{id:GestureId;symbol:string;hint:string}[]=[
{id:'TRIANGLE',symbol:'△',hint:'Pouces et index joints'},
{id:'CIRCLE',symbol:'○',hint:'Mains en anneau'},
{id:'SPIRAL',symbol:'⌁',hint:'Poignet en vrille'},
{id:'GATE',symbol:'◇',hint:'Paumes en portail'}
];
const LEVEL_LENGTHS=[3,4,5] as const;
export default function TrainingLab({kind,onBack}:{kind:Training;onBack:()=>void}){if(kind==='stereo')return <Stereo onBack={onBack}/>;if(kind==='oculus')return <Oculus onBack={onBack}/>;return <Hands onBack={onBack}/>}
function Head({id,title,onBack}:{id:string;title:string;onBack:()=>void}){return <header className="training-head"><button onClick={onBack}>← LABO</button><div><p>{id} · TRAINING</p><h2>{title}</h2></div><span className="badge">TRAINING</span></header>}
function Stereo({onBack}:{onBack:()=>void}){const[level,setLevel]=useState(1);const canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=canvas.current;if(!c)return;const dpr=Math.min(devicePixelRatio||1,2),w=360,h=190;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');if(!x)return;x.scale(dpr,dpr);const period=Math.max(34,58-level*3),rng=new Uint32Array(w*h);crypto.getRandomValues(rng);const img=x.createImageData(w,h);const data=img.data;const depth=(px:number,py:number)=>{const nx=(px-w/2)/(w*.28),ny=(py-h/2)/(h*.42);const tri=ny>.72-Math.abs(nx)*1.45&&ny<.7&&Math.abs(nx)<.95;const eye=((nx*.9)**2+(ny+.12)**2)<.18;return tri||eye?Math.min(9,2+level):0};for(let py=0;py<h;py++){for(let px=0;px<w;px++){let source=px%period;if(px>=period){const dep=depth(px,py);source=Math.max(0,px-period+dep)}const i=(py*w+px)*4,si=(py*w+source)*4;if(px>=period){data[i]=data[si];data[i+1]=data[si+1];data[i+2]=data[si+2]}else{const v=35+(rng[py*w+px]%185);data[i]=v*.35;data[i+1]=v;data[i+2]=v*.55}data[i+3]=255}}x.putImageData(img,0,0)},[level]);return <main className="training-screen"><Head id="FLI-STEREO" title="Third Eye" onBack={onBack}/><section className="training-panel stereo-training"><h1>Quelque chose est caché ici.</h1><p>Commencez par les deux repères : regardez au-delà de l’écran jusqu’à percevoir trois points. Gardez le point central, puis descendez doucement vers le motif.</p><div className="fusion-dots"><b>●</b><b>●</b></div><canvas ref={canvas} className="autostereo"/><div className="level-row"><button onClick={()=>setLevel(Math.max(1,level-1))}>−</button><b>DEPTH {level} / 6</b><button onClick={()=>setLevel(Math.min(6,level+1))}>＋</button></div><details><summary>RÉVÉLER LA CIBLE</summary><p>Un triangle contenant un œil stylisé. Si vous ne le voyez pas, ce n’est pas un échec : la fusion stéréoscopique varie beaucoup selon les personnes et l’écran.</p></details><small>Exercice ludique de fusion binoculaire, pas une rééducation orthoptique. Ne prolongez pas l’effort : arrêtez en cas de douleur, vision double persistante, nausée ou mal de tête.</small></section></main>}
function Oculus({onBack}:{onBack:()=>void}){const[running,setRunning]=useState(false);const[seconds,setSeconds]=useState(30);useEffect(()=>{if(!running)return;const t=window.setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);return 30}return s-1}),1000);return()=>clearInterval(t)},[running]);return <main className="training-screen"><Head id="FLI-OCULUS" title="Oculus" onBack={onBack}/><section className="training-panel"><h1>Suivez. Respirez. Clignez.</h1><p>Gardez la tête immobile et suivez doucement le point avec les yeux. Aucun mouvement ne doit être douloureux.</p><div className={`oculus-field ${running?'run':''}`}><i>●</i></div><button className="primary big" onClick={()=>setRunning(!running)}>{running?`${seconds}s · STOP`:'30s · COMMENCER'}</button><small>Détente et coordination visuelle uniquement. Cet exercice ne corrige pas la myopie, le strabisme ou une maladie oculaire et ne remplace pas un ophtalmologiste/orthoptiste.</small></section></main>}
function randomSequence(n:number):GestureId[]{return Array.from({length:n},()=>gestureDefs[Math.floor(Math.random()*gestureDefs.length)]!.id)}
function GestureCard({id,index,active}:{id:GestureId;index?:number;active?:boolean}){const g=gestureDefs.find(x=>x.id===id)!;return <div className={`hand-card ${active?'active':''}`}>{index!==undefined&&<span>{String(index+1).padStart(2,'0')}</span>}<b>{g.symbol}</b><small>{g.id}</small></div>}
function Hands({onBack}:{onBack:()=>void}){const[level,setLevel]=useState(0);const[sequence,setSequence]=useState<GestureId[]>(()=>randomSequence(LEVEL_LENGTHS[0]));const[phase,setPhase]=useState<'observe'|'input'|'result'|'done'>('observe');const[cursor,setCursor]=useState(0);const[answers,setAnswers]=useState<GestureId[]>([]);const[scores,setScores]=useState<number[]>([]);const len=LEVEL_LENGTHS[level];
useEffect(()=>{if(phase!=='observe')return;setCursor(0);const t=window.setInterval(()=>setCursor(c=>(c+1)%sequence.length),900);return()=>clearInterval(t)},[phase,sequence]);
const startLevel=useCallback((lv:number)=>{setLevel(lv);setSequence(randomSequence(LEVEL_LENGTHS[lv]));setAnswers([]);setPhase('observe')},[]);
const levelScore=useMemo(()=>answers.filter((a,i)=>a===sequence[i]).length,[answers,sequence]);const perfect=answers.length===len&&levelScore===len;const total=scores.reduce((a,b)=>a+(b??0),0);
function tap(id:GestureId){if(phase!=='input'||answers.length>=len)return;const next=[...answers,id];setAnswers(next);if(next.length===len){const s=next.filter((a,i)=>a===sequence[i]).length;setScores(prev=>{const copy=[...prev];copy[level]=s;return copy});setPhase('result')}}
function reset(){setScores([]);startLevel(0)}
return <main className="training-screen"><Head id="FLI-HAND" title="Hand Codex" onBack={onBack}/><section className="training-panel hand-game">
<div className="hand-progress"><div>{LEVEL_LENGTHS.map((_,i)=><i key={i} className={i<=level||phase==='done'?'on':''}/>)}</div><span>NIVEAU {Math.min(level+1,3)}/3</span></div>
{phase==='observe'&&<><p className="section-kicker">PHASE 1 · OBSERVE</p><h1>Mémorise l’ordre des {len} gestes.</h1><div className="hand-sequence">{sequence.map((id,i)=><GestureCard key={i} id={id} index={i} active={i===cursor}/>)}</div><p className="hand-hint">{gestureDefs.find(g=>g.id===sequence[cursor])?.hint}</p><button className="primary big" onClick={()=>setPhase('input')}>C’EST MÉMORISÉ</button></>}
{(phase==='input'||phase==='result')&&<><p className="section-kicker">PHASE 2 · REPRODUIRE</p><div className="hand-slots">{Array.from({length:len}).map((_,i)=>{const a=answers[i],wrong=phase==='result'&&a!==sequence[i];return <div key={i} className={`hand-slot ${wrong?'wrong':a?'filled':''}`}>{a?gestureDefs.find(g=>g.id===a)!.symbol:i+1}{phase==='result'&&wrong&&<small>{gestureDefs.find(g=>g.id===sequence[i])!.symbol}</small>}</div>})}</div>
{phase==='input'?<><div className="hand-pad">{gestureDefs.map(g=><button key={g.id} onClick={()=>tap(g.id)}><b>{g.symbol}</b><span>{g.id}</span></button>)}</div><button className="hand-undo" onClick={()=>setAnswers(a=>a.slice(0,-1))}>EFFACER LE DERNIER</button></>:<><h1>SCORE NIVEAU : {levelScore}/{len}</h1><p>{perfect?'Séquence exacte. Passage au niveau suivant.':'L’ordre attendu apparaît sous les erreurs.'}</p><button className="primary big" onClick={()=>{if(perfect){if(level===2)setPhase('done');else startLevel(level+1)}else{setAnswers([]);setPhase('observe')}}}>{perfect?(level===2?'VOIR LE RÉSULTAT':'NIVEAU SUIVANT'):'RÉESSAYER'}</button></>}</>}
{phase==='done'&&<><p className="section-kicker">FLI-HAND · SESSION CLOSE</p><div className="hand-sigil">◇</div><h1>RITUEL TERMINÉ</h1><div className="hand-total">{total}/12</div><p>« Rien de magique ici, juste ta mémoire qui apprend à tenir le rythme. » — Marty</p><button className="primary big" onClick={reset}>RECOMMENCER</button></>}
<small>Gestes inventés pour FeuchLab. Aucun pouvoir magique revendiqué.</small></section></main>}
